### PR TITLE
fix: add external js to header

### LINKED ISSUE #45: APlayer、Dplayer 报错
APlayer
DPlayer

### PR DESCRIPTION
**Pull request by simonsmh**
dirty hack to fix #45

### CODE REVIEW

File: src/fileView.js [hunk 1]
```diff
@@ -33,10 +33,9 @@ function renderPDFPreview(file) {
             <i class="fas fa-spinner fa-pulse"></i>
             <span id="loading-progress">Loading PDF...</span>
           </div>
-          <script src="https://cdn.jsdelivr.net/gh/pipwerks/PDFObject/pdfobject.min.js"></script>
           <script>
-          const loadingLabel = document.querySelector('.loading-label')
-          const loadingProgress = document.querySelector('#loading-progress')
+          loadingLabel = document.querySelector('.loading-label')
+          loadingProgress = document.querySelector('#loading-progress')
```
Comment (spencerwooo) [inline src/fileView.js:38]: Why are we deleting the `const` declarations?

Comment (simonsmh) [reply src/fileView.js:38]: It's causing exception. Open 1.pdf, then return to folder, than 2.pdf could reproduce.

**Review by spencerwooo — APPROVED** [review]
👍
